dist: bionic
language: java
jdk: openjdk13

install:
  - java --version

services:
  - postgresql

before_script:
  - psql -c "create role kdbi with superuser login password 'kdbi'; create database kdbi;" -U postgres

env:
  - database_url="jdbc:postgresql://postgres:5432/kdbi"

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)